### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by chintan-mishra** [pibico/pibical#3]
ERPNext and NextCloud both are set up with the same timezone for a user. However, when an event is created in either of the applications, then the schedule in the other app adjusts for the timezones.

How can the two applications
- avoid modifying the time schedules, or
- identify timezone appropriately?

Pibical branch: version-13

**Comment by pibico** [comment]
We have modified code in synchronizing events in order not to duplicate them. Please check installing the update
