### ISSUE TITLE
CardDav support

### ISSUE THREAD

**Issue by rasos** [pibico/pibical#4]
Thank you for this amazing ERPnext app! For a full integration with nextcloud we also would need to sync contacts with CardDav. Any considerations to extend the app acting as a CardDav client (using the same credentials)? ERPnext currently only allows syncing contacts with a Google account, which we do not want for GDPR reasons.  Some users might even support such an effort, see https://github.com/frappe/frappe/issues/339#issuecomment-610703298

**Comment by pibico** [comment]
This is a future plan for NextCloud Integration with ERPNext. Hopefully along 2022 we'll try to implement this evolution with Contacts Integration through CardDav and improve CalDav Integration for asynchronous syncing.

**Comment by pibico** [comment]
No news up to now. It is still on the roadmap but without any committed date

**Comment by rasos** [comment]
There is now an extra App for CardDav support available https://github.com/pibico/frappe_carddav :fireworks:
