### ISSUE TITLE
CalDav Credentials section is missing

### ISSUE THREAD

**Issue by amecreate** [pibico/pibical#5]
ERPNext version 13
Frappe version 13
PibiCal: v0.0.1 (version-13)

User page does not have CalDav Credentials section nor the CalDav URL, CalDav Username, or CalDav Token fields. They are not in the custom_field.json file either.

Is it possible that the above fields are not in the pibiCal app as changes on core DocType like User are directly updated in code?

**Comment by pibico** [comment]
Updated custom_field.json with needed data for User
