### ISSUE TITLE
ERPnext14 support

### ISSUE THREAD

**Issue by rasos** [pibico/pibical#6]
Has anybody tested or are there plans for official support of pibical for ERPnext14?

**Comment by pibico** [comment]
Not for the moment. We have not still migrated to ERPNext 14 nor Frappe 
14 in any server.

**Comment by pibico** [comment]
> Has anybody tested or are there plans for official support of pibical for ERPnext14?

We have just installed pibical branch version-13 on ERPNext14 and it's running without issues.

On installing the app you must choose version-13 with the following command from frappe-bench folder:
`bench get-app pibical --branch version-13 https://github.com/pibico/pibical`

![imagen](https://user-images.githubusercontent.com/69711454/192116218-9d2e9b38-e9cb-4a08-8985-4a1e53071f9f.png)
